config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :sights

  resources :users

  resources :getaways do
    resources :stops do
      resources :adventures do

      end
    end
  end

  root 'application#index'
  post '/login' => 'application#login'
  get '/logout' => 'application#logout'
end

app/models/stop.rb
# create_table :stops do |t|
#   t.belongs_to :getaway
#   t.belongs_to :city
#   t.datetime :arrival
#   t.datetime :departure
# end

class Stop < ActiveRecord::Base
  include DateHelper

  belongs_to :city
  belongs_to :getaway

  has_many :adventures

  def name
    city.name
  end

  # TODO: Have this return the full language names
  def country
    return nil if city.blank?
    city.country
  end

  def sights
    return [] if adventures.blank?
    adventures.map(&:sight)
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_getaway
  before_action :set_stop, only: [:show, :edit, :update, :destroy]
  before_action :set_cities, only: [:new, :edit]

  # GET /getaways/:getaway_id/stops
  def index
    @stops = @getaway.stops
  end

  # GET /getaways/:getaway_id/stops/1
  def show
  end

  # GET /getaways/:getaway_id/stops/new
  def new
    @stop = Stop.new(getaway: @getaway)
  end

  # GET /getaways/:getaway_id/stops/1/edit
  def edit
  end

  # POST /getaways/:getaway_id/stops
  def create
    @stop = Stop.new(stop_params)

    if @stop.save
      redirect_to getaway_stop_url(@getaway, @stop), notice: 'Stop was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /getaways/:getaway_id/stops/1
  def update
    if @stop.update(stop_params)
      redirect_to getaway_stop_url(@getaway, @stop), notice: 'Stop was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /getaways/:getaway_id/stops/1
  def destroy
    @stop.destroy
    redirect_to getaway_stops_url(@getaway), notice: 'Stop was successfully destroyed.'
  end

  private
    def set_getaway
      @getaway = Getaway.find(params[:getaway_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.where( id: params[:id], getaway_id: @getaway.id ).first
    end

    def set_cities
      @cities = City.name_sorted
    end

    # Only allow a trusted parameter "white list" through.
    def stop_params
      params.require(:stop).permit(:city_id, :arrival, :departure).merge(getaway_id: @getaway.id)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for [@getaway, @stop] do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :arrival, "Arrive" %>
    <%= f.datetime_select :arrival, :ampm => true, :minute_step => 15 %>
  </div>

  <div>
    <%= f.label :departure , "Depart" %>
    <%= f.datetime_select :departure, :ampm => true, :minute_step => 15 %>
  </div>

  <div>
    <%= f.label :city_id %>
    <%= f.select :city_id, @cities.map { |c| [ c.display_name, c.id ] }, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<%= link_to 'Show', getaway_stop_path(@getaway, @stop) %> |
<%= link_to 'Back', getaway_path(@getaway.id) %>

<h2>Editing Stop</h2>

<%= render 'form' %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stops</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= link_to stop.name, getaway_stop_path(@getaway, stop) %></td>
        <td><%= link_to 'Edit', edit_getaway_stop_path(@getaway, stop) %></td>
        <td><%= link_to 'Destroy', getaway_stop_path(@getaway, stop), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_getaway_stop_path(@getaway) %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form' %>

<%= link_to 'Back', getaway_path(@getaway.id) %>

app/views/stops/show.html.erb
<%= link_to 'Edit', edit_getaway_stop_path(@getaway, @stop) %> |
<%= link_to 'Destroy', getaway_stop_path(@getaway, @stop), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', getaway_path(@getaway) %>

<h2><%= @stop.name %></h2>
<h5><%= @stop.duration_string %> (<%= @stop.duration %> hours)</h5>
<p id="notice"><%= notice %></p>

<ul>
  <lh>General Information:</lh>
  <li>Locals call "<%= @stop.country.name %>": <%= @stop.country.local_name %></li>
  <li>Currency: <%= @stop.country.currency.code %></li>
  <li>Languages spoken: <%= @stop.country.languages.join(', ') %></li>
  <li>Country dialing code: +<%= @stop.country.country_code %></li>
</ul>

<br/>

<%= link_to 'New Adventure', new_getaway_stop_adventure_path(@getaway, @stop) %>

<% if @stop.adventures.blank? %>
  <div>You currently don't have any adventures scheduled in <%= @stop.name %> :(</div>
  <br/>
<% else%>
  <% @adventures = @stop.adventures %>
  <ul>
    <lh>Adventures</lh>
    <% @adventures.each do |adventure| %>
      <li>
        <a href="<%= getaway_stop_adventure_path(@getaway, @stop, adventure) %>">
          <%= adventure.sight.name %>
        </a>
        <span> - <%= adventure.description %></span>
      </li>
    <% end %>
  </ul>
<% end %>

<div id='map'></div>

<script type='text/javascript'>
  var city = '<%= @stop.city.to_json %>';
  var sights = '<%= @stop.sights.to_json %>';

  // TODO: Fix this horrible hack
  while (city.includes('&quot;')) { city = city.replace('&quot;', '"'); }
  while (sights.includes('&quot;')) { sights = sights.replace('&quot;', '"'); }

  city = JSON.parse(city);
  sights = JSON.parse(sights);
</script>

<%= javascript_include_tag @google_maps_url %>