config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :sights

  resources :users

  resources :getaways do
    resources :stops do
      resources :adventures do

      end
    end
  end

  root 'application#index'
  post '/login' => 'application#login'
  get '/logout' => 'application#logout'
end

app/models/sight.rb
class Sight < ActiveRecord::Base

  has_many :adventures
  belongs_to :city

end

app/controllers/sights_controller.rb
class SightsController < ApplicationController
  before_action :set_sight, only: [:show, :edit, :update, :destroy]

  # GET /sights
  def index
    @sights = Sight.all
  end

  # GET /sights/1
  def show
  end

  # GET /sights/new
  def new
    @sight = Sight.new
  end

  # GET /sights/1/edit
  def edit
  end

  # POST /sights
  def create
    @sight = Sight.new(sight_params)

    if @sight.save
      redirect_to sight_url(@sight), notice: 'Sight was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sights/1
  def update
    if @sight.update(sight_params)
      redirect_to @sight, notice: 'Sight was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sights/1
  def destroy
    @sight.destroy
    redirect_to sights_url, notice: 'Sight was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sight
      @sight = Sight.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sight_params
      params.require(:sight).permit(:name, :type)
    end
end

app/helpers/sights_helper.rb
module SightsHelper
end

app/views/sights/_form.html.erb
<%= form_for(@sight) do |f| %>
  <% if @sight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sight.errors.count, "error") %> prohibited this sight from being saved:</h2>

      <ul>
      <% @sight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sights/edit.html.erb
<h1>Editing Sight</h1>

<%= render 'form' %>

<%= link_to 'Show', @sight %> |
<%= link_to 'Back', sights_path %>

app/views/sights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sights</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sights.each do |sight| %>
      <tr>
        <td><%= link_to sight.name, sight_path(sight) %></td>
        <td><%= link_to 'Edit', edit_sight_path(sight) %></td>
        <td><%= link_to 'Destroy', sight_path(sight), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sight', new_sight_path %>

app/views/sights/new.html.erb
<h1>New Sight</h1>

<%= render 'form' %>

<%= link_to 'Back', sights_path %>

app/views/sights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sight_path(@sight) %> |
<%= link_to 'Back', sights_path %>

<div id='map'></div>

<script type='text/javascript'>
  var city = '<%= @sight.city.to_json %>';
  var sight = '<%= @sight.to_json %>';

  // TODO: Fix this horrible hack
  while (city.includes('&quot;')) { city = city.replace('&quot;', '"'); }
  while (sight.includes('&quot;')) { sight = sight.replace('&quot;', '"'); }

  city = JSON.parse(city);
  sight = JSON.parse(sight);

  console.log(city);
  console.log(sight);
</script>

<%= javascript_include_tag @google_maps_url %>