config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :sights

  resources :users

  resources :getaways do
    resources :stops do
      resources :adventures do

      end
    end
  end

  root 'application#index'
  post '/login' => 'application#login'
  get '/logout' => 'application#logout'
end

app/models/adventure.rb
# create_table "adventures", force: :cascade do |t|
#   t.integer  "sight_id"
#   t.integer  "stop_id"
#   t.text     "description"
#   t.integer  "rating"
#   t.datetime "created_at",   null: false
#   t.datetime "updated_at",   null: false
#   t.boolean  "completed", default: false
# end

# add_index "adventures", ["stop_id"], name: "index_adventures_on_stop_id"

class Adventure < ActiveRecord::Base

  belongs_to :stop
  belongs_to :sight

  has_one :user, as: :promoter

end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_getaway
  before_action :set_stop
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]
  before_action :set_sights, only: [:new, :edit]

  # GET /getaways/:getaway_id/stops/:stop_id/adventures
  # GET /getaways/:getaway_id/stops/:stop_id/adventures.json
  def index
    @adventures = Adventure.where(stop_id: @stop.id)
  end

  # GET /getaways/:getaway_id/stops/:stop_id/adventures/1
  # GET /getaways/:getaway_id/stops/:stop_id/adventures/1.json
  def show
  end

  # GET /getaways/:getaway_id/stops/:stop_id/adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /getaways/:getaway_id/stops/:stop_id/adventures/1/edit
  def edit
  end

  # POST /getaways/:getaway_id/stops/:stop_id/adventures
  # POST /getaways/:getaway_id/stops/:stop_id/adventures.json
  def create
    @adventure = Adventure.new(adventure_params.merge(stop_id: @stop.id))

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to getaway_stop_adventure_url(@getaway, @stop, @adventure), notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /getaways/:getaway_id/stops/:stop_id/adventures/1
  # PATCH/PUT /getaways/:getaway_id/stops/:stop_id/adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params.merge(stop_id: @stop.id))
        format.html { redirect_to getaway_stop_adventure_url(@getaway, @stop, @adventure), notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getaways/:getaway_id/stops/:stop_id/adventures/1
  # DELETE /getaways/:getaway_id/stops/:stop_id/adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to getaway_stop_adventures_url(@getaway, @stop), notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_getaway
      @getaway = Getaway.find(params[:getaway_id])
    end

    def set_stop
      @stop = Stop.find(params[:stop_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    def set_sights
      @sights = @stop.city.nearby_sights
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:getaway_id, :stop_id, :sight_id, :description)
    end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_form.html.erb
<%= form_for [@getaway, @stop, @adventure] do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :sight_id, "Sights near #{@stop.city.name}:" %>
    <%= f.select :sight_id, @sights.map { |s| [ "#{s.name} - #{s.distance.round(2)} km", s.id ] }, include_blank: true %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<%= link_to 'Show', getaway_stop_adventure_path(@getaway, @stop, @adventure) %> |
<%= link_to 'Back', getaway_stop_adventures_path(@getaway, @stop) %>

<h2>Editing Adventure</h2>

<%= render 'form' %>

app/views/adventures/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', getaway_path(@getaway) %>

<h2>Adventures in <%= @stop.name %></h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= link_to adventure.sight.name, getaway_stop_adventure_path(@getaway, @stop, adventure) %></td>
        <td><%= link_to 'Edit', edit_getaway_stop_adventure_path(@getaway, @stop, adventure) %></td>
        <td><%= link_to 'Destroy', getaway_stop_adventure_path(@getaway, @stop, adventure), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_getaway_stop_adventure_path(@getaway, @stop) %>

app/views/adventures/new.html.erb
<%= link_to 'Back', getaway_stop_path(@getaway, @stop) %>

<h1>New Adventure</h1>

<%= render 'form' %>

app/views/adventures/show.html.erb
<%= link_to 'Edit', edit_getaway_stop_adventure_path(@getaway, @stop, @adventure) %> |
<%= link_to 'Back', getaway_stop_adventures_path(@getaway, @stop) %>

<h2><%= @adventure.sight.name %></h2>
<p id="notice"><%= notice %></p>

<div>Description: <%= @adventure.description %></div>
<div>City: <%= @adventure.stop.name %></div>

<% map_url = <<-STR
  https://maps.googleapis.com/maps/api/staticmap?center=#{@adventure.sight.coords}&zoom=15&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C#{@adventure.sight.coords}&key=#{GOOGLE_MAPS_API_KEY}
STR
%>

<img src="<%= map_url %>" class='static-map img-fluid img-rounded' alt="<%= @adventure.sight.name %>" />


<div>Maybe some reviews go here</div>
<div>Maybe a list of friends that recommended it</div>