config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :sights

  resources :users

  resources :getaways do
    resources :stops do
      resources :adventures do

      end
    end
  end

  root 'application#index'
  post '/login' => 'application#login'
  get '/logout' => 'application#logout'
end

app/models/getaway.rb
# create_table "getaways", force: :cascade do |t|
#   t.integer  "user_id"
#   t.string   "name"
#   t.text     "description"
#   t.datetime "arrival"
#   t.datetime "departure"
#   t.datetime "created_at",     null: false
#   t.datetime "updated_at",     null: false
#   t.boolean  "is_public",   default: false
# end

class Getaway < ActiveRecord::Base
  include DateHelper

  has_many :users
  has_many :stops

  scope :all_public, -> { where(is_public: true) }

  # All cities that will be visited
  # Returns Array of City instances.
  def visiting_cities
    return [] if stops.blank?

    cities = []
    sights = stops.map(&:sights)

    if sights.present?
      cities = sights.flatten.map(&:city).uniq
    end

    cities
  end

  # All countries that will be visited
  # Returns Array of ISO3166::Country instances.
  def visiting_countries
    cities = visiting_cities
    return [] if cities.blank?

    cities.map(&:country).uniq(&:name)
  end
end

app/controllers/getaways_controller.rb
class GetawaysController < ApplicationController
  before_action :set_getaway, only: [:show, :edit, :update, :destroy]

  # GET /getaways
  # GET /getaways.json
  def index
    @getaways = Getaway.all_public
  end

  # GET /getaways/1
  # GET /getaways/1.json
  def show
  end

  # GET /getaways/new
  def new
    @getaway = Getaway.new
  end

  # GET /getaways/1/edit
  def edit
  end

  # POST /getaways
  # POST /getaways.json
  def create
    @getaway = Getaway.new(getaway_params)

    respond_to do |format|
      if @getaway.save
        format.html { redirect_to @getaway, notice: 'Getaway was successfully created.' }
        format.json { render :show, status: :created, location: @getaway }
      else
        format.html { render :new }
        format.json { render json: @getaway.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /getaways/1
  # PATCH/PUT /getaways/1.json
  def update
    respond_to do |format|
      if @getaway.update(getaway_params)
        format.html { redirect_to @getaway, notice: 'Getaway was successfully updated.' }
        format.json { render :show, status: :ok, location: @getaway }
      else
        format.html { render :edit }
        format.json { render json: @getaway.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getaways/1
  # DELETE /getaways/1.json
  def destroy
    @getaway.destroy
    respond_to do |format|
      format.html { redirect_to getaways_url, notice: 'Getaway was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_getaway
      @getaway = Getaway.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def getaway_params
      params.require(:getaway).permit(:name, :arrival, :departure, :is_public)
    end
end

app/helpers/getaways_helper.rb
module GetawaysHelper
end

app/views/getaways/_form.html.erb
<%= form_for(@getaway) do |f| %>
  <% if @getaway.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@getaway.errors.count, "error") %> prohibited this getaway from being saved:</h2>

      <ul>
      <% @getaway.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :arrival, "Arrive" %>
    <%= f.datetime_select :arrival, :ampm => true, :minute_step => 15 %>
  </div>

  <div>
    <%= f.label :departure , "Depart" %>
    <%= f.datetime_select :departure, :ampm => true, :minute_step => 15 %>
  </div>

  <div>
    <%= f.label :is_public, "Viewable by everyone:" %>
    <%= f.check_box :is_public, default: false %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/getaways/edit.html.erb
<h1>Editing Getaway</h1>

<%= render 'form' %>

<%= link_to 'Show', @getaway %> |
<%= link_to 'Back', getaways_path %>

app/views/getaways/index.html.erb
<h2>Getaways</h2>
<p id="notice"><%= notice %></p>

<%= link_to 'New Getaway', new_getaway_path %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @getaways.each do |getaway| %>
      <tr>
        <td><%= link_to getaway.name, getaway %></td>
        <td><%= link_to 'Edit', edit_getaway_path(getaway) %></td>
        <td><%= link_to 'Destroy', getaway, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/getaways/new.html.erb
<%= link_to 'Back', getaways_path %>

<h1>New Getaway</h1>

<%= render 'form' %>

app/views/getaways/show.html.erb
<%= link_to 'Edit', edit_getaway_path(@getaway) %> |
<%= link_to 'Back', getaways_path %>

<h2><%= @getaway.name %></h2>
<h5><%= @getaway.duration_string %> (<%= @getaway.duration(:days) %> days)</h5>
<p id="notice"><%= notice %></p>


<%
  countries =  @getaway.visiting_countries
  cities = @getaway.visiting_cities
%>
<ul>
  <lh>Overview:</lh>
  <li>Cities: <%= cities.map(&:name).join(', ') %> (<%= cities.count %>)</li>
  <li>Countries: <%= countries.map(&:name).join(', ') %> (<%= countries.count %>)</li>
  <li>Currencies: <%= countries.map(&:currency).uniq.map(&:code).join(', ') %></li>
  <li>Languages: <%= countries.map(&:languages).flatten.uniq.join(', ') %></li>
</ul>

<br/>

<%= link_to 'New Stop', new_getaway_stop_path(@getaway) %>

<% if @getaway.stops.blank? %>
  <div>This getaway doesn't currently have any stops.</div>
<% else%>
  <% @stops = @getaway.stops.order(:arrival) %>
  <ul>
    <% @stops.each do |stop| %>
      <li>
        <a href="<%= getaway_stop_path(@getaway, stop) %>">
          <%= stop.city.name %> - <%= stop.duration_string %>
        </a>
        <% adventures = stop.adventures %>
        <% if adventures.present? %>
          <ul>
            <% adventures.each do |adventure| %>
              <li>
                <a href="<%= getaway_stop_adventure_path(@getaway, stop, adventure.id) %>">
                  <%= adventure.sight.name %>
                </a>
              </li>
            <% end %>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>